package org.example.Exceptions;

import java.sql.SQLException;

public class Client {
    // throws -> to declare that a function throws an exception
    // throw -> to actually throw an exception
    public static void main(String[] args) throws SQLException{
        try{
            Util.demo(0);
            //opened a db connection
//            throw new MyCustomException("This is an exception generated by me");
        }
        catch(ArithmeticException e){
            System.out.println("Arithmetic Error in main :"+ e.getMessage());
            throw e;
        }
        catch(SQLException e){
            System.out.println("SQL Error " + e.getMessage());
            throw e;
        }
        catch(MyCustomException e){
            System.out.println("Custom Error " + e.getMessage());
            throw e;
        }
        finally {
            System.out.println("Close DB connection");
        }

        //close db connection - if catch block gets error and throws it this line will not get called
//        System.out.println("Close DB connection");

    }
}
